import React, { useEffect } from 'react';
import worldMap from '../images/worldMap.svg';
import imageMapResize from 'image-map-resizer';
//Image Map Generated by http://www.image-map.net/ 

    const Graph = () => {

        const imageClick = () => {
            console.log("click");
        }
        
        useEffect(() => {
            imageMapResize('[name="image-map"]');
        }, []);
    
        return (
             <div className='map'>
             <img useMap='#image-map' className='map' src = {worldMap} onClick={imageClick}></img>
                <map name="image-map">
                    <area target="" alt="South America" title="South America" href="SA" coords="277,388,251,435,257,469,301,537,315,596,329,684,352,714,417,725,424,691,411,616,445,585,478,530,486,480,485,436,387,388,308,347,295,358,284,370" shape="poly"></area>
                    <area target="" alt="North America" title="North America" href="NA" coords="267,387,216,368,158,340,104,309,77,261,83,188,97,150,29,152,7,137,9,88,72,45,141,37,263,35,321,34,349,38,375,82,409,96,454,116,447,160,416,208" shape="poly"></area>
                    <area target="" alt="Africa" title="Africa" href="AF" coords="622,242,588,272,564,307,561,344,573,382,629,406,669,408,686,411,696,462,700,508,699,552,730,610,751,627,816,632,866,598,901,555,917,480,918,436,911,384,911,360,852,317,818,272,777,229,695,215" shape="poly"></area>
                    <area target="" alt="Europe" title="Europe" href="EU" coords="625,114,603,168,591,194,608,224,625,231,662,211,684,196,715,207,722,217,742,220,785,214,807,187,819,141,781,120,792,81,772,27,688,52" shape="poly"></area>
                    <area target="" alt="Asia" title="Asia" href="AS" coords="780,33,797,79,785,116,823,139,829,192,914,227,975,246,1003,266,1012,309,1009,368,1040,414,1101,477,1302,468,1234,339,1306,275,1347,149,1379,72,1288,33,914,12" shape="poly"></area>
                    <area target="" alt="Middle East" title="Middle East" href="ME" coords="848,214,805,201,788,212,798,232,821,259,828,283,869,327,897,341,928,341,952,302,981,287,968,253,906,225,873,214,857,210" shape="poly"></area>
                    <area target="" alt="Australia" title="Australia" href="AU" coords="1270,490,1219,517,1186,578,1185,610,1245,650,1305,667,1371,637,1396,581,1390,520,1349,476" shape="poly"></area>
                    <area target="" alt="New Zealand" title="New Zealand" href="NZ" coords="" shape="poly"></area>
                </map>
             </div>
             
          );
         }
export default Graph;
